[package]
name = "paystream"
version = "0.1.0"
edition = "2023_10"

authors = ["Your Name <you@example.com>"]

[dependencies]
starknet = ">=2.6.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.12.0" }

[scripts]
# Add build/test scripts if needed later

[lib]
name = "paystream"
path = "src/lib.cairo"

[tool.snforge]
# If using snforge later, config can be added here