name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: latest

      - name: Build contracts
        working-directory: contracts
        run: |
          scarb --version
          scarb build

      - name: Run tests
        working-directory: contracts
        run: |
          scarb test
